### ISSUE TITLE
Trying to get Legacy Edge working on Windows 11

### ISSUE THREAD

**Issue by Lights7605** [Legacy-Edge/Legacy-Edge-Launcher#8] opened 2023-08-07 08:57 UTC
Hello, so is there a way to get legacy edge running on Windows 11? Here is where I am at so far

- I have uninstalled Chromium Edge
- I have copied the Legacy Edge files from a copy of Windows 10 2004
- I have deleted the AppData files for Edge
- I have ran the following powershell commands
Get-AppXPackage -AllUsers -Name Microsoft.MicrosoftEdge | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register “$($_.InstallLocation)\AppXManifest.xml” -Verbose}
Get-AppXPackage -AllUsers -Name Microsoft.MicrosoftEdgeDevToolsClient | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register “$($_.InstallLocation)\AppXManifest.xml” -Verbose}
- I have disabled CodeIntergirty by using this trick https://learn.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-test-windows-s#first-download-the-policies-and-then-choose-one

Edge will open but it will not show any elements of the browser and will eventually crash what could be causing this issue? What files do I need to add or replace? Any help will be greatly appreciated. 
![vmware_hFDPliLFN4](https://github.com/Legacy-Edge/Legacy-Edge-Launcher/assets/96835147/01646f25-4565-44d4-835a-08cc7d9a21ab)

**Comment by ShortDevelopment** [comment] 2023-08-07 09:03
> **Warning**   
> Disabling Code-Integrity is really bad!

Legacy Edge seems to use an internal component that has been changed in Win11.
AFAIK there's no (easy) solution to fix this...

Duplicate of #2

**Closed** 2023-08-07 09:04 UTC

**Comment by ShortDevelopment** [comment] 2023-08-10 06:16
There is no real solution.
You would likely have to patch the edge executable...
